### ISSUE TITLE
Projects in orgs not being automatically updated?

### ISSUE THREAD

**Issue by iantrich** [infrastrux/haindex#3]
All my components and cards are in the custom-components and custom-cards orgs respectively. Is there an issue with authorizing these or just a bug in general?

![image](https://user-images.githubusercontent.com/1287159/53709879-3a447d80-3e00-11e9-870b-98b633952a46.png)

**Comment by lociii** [comment]
True true. Same as in #4 I didn't take orgs into consideration. Will check if I can get a list of admins for that org and use their accounts to subscribe.

**Comment by lociii** [comment]
I wanted to use the repo collaborators list to get repo admins (to list them and use a registered one for subscription) but somehow GitHub won't let me read the list with your credentials - even that you have push permissions... https://developer.github.com/v3/repos/collaborators/#list-collaborators
Will investigate further.
