### ISSUE TITLE
Author link not valid if in an org

### ISSUE THREAD

**Issue by iantrich** [infrastrux/haindex#4]
All my components/cards are in orgs and as such the inferred author link is not accurate for

![image](https://user-images.githubusercontent.com/1287159/53709974-b5a62f00-3e00-11e9-915a-b175a3ee3e01.png)

It is linking to https://github.com/custom-components instead of https://github.com/iantrich, which is understandable, but not true to me in this case.

Perhaps allow for this to be overridden in the package.yaml?

**Comment by lociii** [comment]
Good point. Didn't think about organizations when designing the data structure. Will add an update soon.
